### ISSUE TITLE
Grouping of media queries

### ISSUE THREAD

**Issue by logankaser** [contivero/hasmin#2]
Hello again, its been some time.

So, grouping media queries, why would that be useful?

Here is an example (Limited to two per breakpoint) from a site I built using my tool, Cell.
As you can see these could be easily combined. Now you might be thinking, surely only generated
CSS would have such waste when it comes to media queries, however anyone using a modular CSS component library or organizing their code by class likely has such repetition. This is mostly due to the common use of a limited set of `breakpoints` that are used as the cutoffs for all media queries in a codebase. For example, one designer may use Large, Medium and Small sizes (each with rem or pixel values) while another may prefer more granularity. Whatever the case, the practice of using a limited set of breakpoints is widespread.
```css
@media all and (min-width: 24rem) {
  .Fz\(s2\)\@xs {font-size: 1.2rem;}
}
@media all and (min-width: 24rem) {
  .Px\(s04\)\@xs {padding-left: .25rem; padding-right: .25rem;}
}
@media all and (min-width: 32rem) {
  .D\(ib\)\@sm {display: inline-block;}
}
@media all and (min-width: 32rem) {
  .Fz\(s1\)\@sm {font-size: 1rem;}
}
@media all and (min-width: 48rem) {
  .D\(b\)\@md {display: block;}
}
@media all and (min-width: 48rem) {
  .D\(ib\)\@md {display: inline-block;}
}
@media all and (min-width: 64rem) {
  .Pos\(s\)\@lg {position: static;}
}
@media all and (min-width: 64rem) {
  .Px\(s1\)\@lg {padding-left: 1rem; padding-right: 1rem;}
}
@media all and (min-width: 80rem) {
  .D\(b\)\@xl {display: block;}
}
@media all and (min-width: 80rem) {
  .D\(n\)\@xl {display: none;}
}
```
So technique is to combine media queries that use the same condition. For example:
```css
@media all and (min-width: 24rem) {
  .Fz\(s2\)\@xs {font-size: 1.2rem;}
  .Px\(s04\)\@xs {padding-left: .25rem; padding-right: .25rem;}
}
@media all and (min-width: 32rem) {
  .D\(ib\)\@sm {display: inline-block;}
  .Fz\(s1\)\@sm {font-size: 1rem;}
}
@media all and (min-width: 48rem) {
  .D\(b\)\@md {display: block;}
  .D\(ib\)\@md {display: inline-block;}
}
@media all and (min-width: 64rem) {
  .Pos\(s\)\@lg {position: static;}
  .Px\(s1\)\@lg {padding-left: 1rem; padding-right: 1rem;}
}
@media all and (min-width: 80rem) {
  .D\(b\)\@xl {display: block;}
  .D\(n\)\@xl {display: none;}
}
```
I never noticed your request for an issue and since you so promptly libraryfied your code I
feel I owe this to you now that I have noticed,
Cheers!

**Comment by contivero** [comment]
Thanks for taking the time! It's been a while since I last looked into CSS stuff, but IIRC one of the issues combining normal rules is the possibility of changing behavior by modifying the cascade.
In this example, you are combining only adjacent rules, which is always safe. Do you know if media queries have some kind of precedence according to their location in the file? In other words, would changing this:
```css
@media all and (min-width: 24rem) {
.Fz\(s2\)\@xs {font-size: 1.2rem;}
}
@media all and (min-width: 32rem) {
.D\(ib\)\@sm {display: inline-block;}
}
@media all and (min-width: 24rem) {
.Px\(s04\)\@xs {padding-left: .25rem; padding-right: .25rem;}
}
```
where there is a query between the two `24rem` queries, into this: 
```css
@media all and (min-width: 24rem) {
.Fz\(s2\)\@xs {font-size: 1.2rem;}
.Px\(s04\)\@xs {padding-left: .25rem; padding-right: .25rem;}
}
@media all and (min-width: 32rem) {
.D\(ib\)\@sm {display: inline-block;}
}
```
be always safe? I believe that in this particular example it is, but I'm not sure if it is always so.

I can look into having adjacent rules merged, but I don't think I'll be getting into more aggressive mergings any time soon. Merging though is quite misleading, because you tend to see big gains in the minified size, but after gzip compression it's either negligible, or it might even be bigger than if no merging had been done.

Anyway, I'll see what I can do.
